# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20171103_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='customermodel',
            name='login',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='secondnname',
            field=models.CharField(default='', max_length=64),
        ),
    ]
