# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20171117_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='computermodel',
            name='picpath',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
