# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_computermodel_picpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='date_completed',
            field=models.DateTimeField(blank=True),
        ),
    ]
