# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-01 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20171130_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computermodel',
            name='picpath',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
